# Generated by Django 4.0 on 2022-12-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addstudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('instagram_link', models.URLField()),
            ],
        ),
    ]
